### ISSUE TITLE
Sequence Repr

### ISSUE THREAD

**Issue by callmest** [BorgwardtLab/PST#2]
Dear Author:
i find PST get better performance than ESM2 with same params in my downstream tasks, and I was wondering that how can I get sequence repr rather than residue repr?

**Comment by callmest** [comment]
sequence level rather than individual residue level

**Comment by claying** [comment]
Hi @callmest 
You can take the average pooling of the residue representations to obtain a protein representation. This can be done easily using the following code:

```
import torch_geometric.nn as gnn

# assume that out is the output of the model
out = gnn.global_mean_pool(out, batch)
```

Please see [here](https://github.com/BorgwardtLab/PST/blob/57d9dcd8200900504a19de459450e137867262d7/experiments/fixed/predict_gearnet.py#L45) for an example.

**Comment by callmest** [comment]
thanks!
